### ISSUE TITLE
MonadState implementation for ParserT?

### ISSUE THREAD

**Issue by colin-adams** [ziman/lightyear#37]
Would it be possible to add an implementation of MonadState for ParserT?

I took a look at the implementation for Monad, and just blinked. I'm not sure I'm up to defining this myself.

**Comment by colin-adams** [comment]
MonadTrans too (then MonadState would be simple)

**Comment by ziman** [comment]
Fixed in 21be4b3c3521f37d557ea05123ad8ffa7fa121d3.
