### ISSUE TITLE
requireFailure consumes an input (does not do backtracking)

### ISSUE THREAD

**Issue by stop-cran** [ziman/lightyear#66]
The documentation claims that `requireFailure` is called `notFollowedBy` in parsec and that it [doesn't consume any input](https://hackage.haskell.org/package/parsec-3.1.13.0/docs/Text-Parsec-Combinator.html#v:notFollowedBy). However, I see it does.

For example, I want to parse a series of any 4 chars. However, these chars shouldn't form a specific string (`"bb"` in an example below). So `"aaaa"` and `"abcd"` should math, but neither `"bbcd"` nor `"abbc"` should not.

I composed a following parser:

```
ntimes 4 (requireFailure (string "bb") *> anyChar)
```

However, I noticed, that it "eats" single b chars. E.g.

```
parse (ntimes 4 (requireFailure (string "bb") *> anyChar)) "abcde"
```

results in `['a', 'c', 'd', 'e']` (it fails, however, on `"bbcd"` and `"abbc"` as expected).

If following implementation of `requireFailure` is used:
```
requireFailure' : ParserT str m tok -> ParserT str m ()
requireFailure' (PT f) = PT requireFailureHelper where
    requireFailureHelper r us cs ue ce ss@(ST i pos tw) =
        f r
            (\t, s => ue [Err pos "argument parser to fail"] s)
            (\t, s => ce [Err pos "argument parser to fail"] s)
            (\errs, _ => us () ss)
            (\errs, _ => cs () ss)
            ss
```

```
parse (ntimes 4 (requireFailure' (string "bb") *> anyToken)) "abcde"
```

gives `['a', 'b', 'c', 'd']` as I expect.

Asked previously on [StackOverflow](https://stackoverflow.com/questions/51739782/idris-lightyear-requirefailure-does-not-do-backtracking).

**Comment by ziman** [comment]
Oh, thank you (and Guillaume), well spotted! I also like that you named the `@`-bound variable differently than `s`.

I'll push the update.

**Comment by ziman** [comment]
Fix pushed, thank you!
